#!/bin/bash

FILES_DIR=files
YT_URL="https://www.youtube.com/watch?v=jm3JFYqvQxw"
CAPTIONS_URL=""

# bash -c "yt-dlp -x --audio-format wav --restrict-filenames --sub-lang en --sub-format json3 --write-auto-sub https://www.youtube.com/watch?v=jm3JFYqvQxw"

bash -c "yt-dlp -x --write-info-json --write-playlist-metafiles --audio-format wav -o %(title)s --restrict-filenames 'https://www.youtube.com/watch?v=jm3JFYqvQxw'"

#yt-dlp -o - "https://www.youtube.com/watch?v=jm3JFYqvQxw" |

#yt-dlp --dump-json "https://www.youtube.com/watch?v=jm3JFYqvQxw" > out.json

#yt-dlp "https://www.youtube.com/watch?v=jm3JFYqvQxw" --config-location ./files/ytdl.conf

#yt-dlp -f best "https://www.youtube.com/watch?v=jm3JFYqvQxw" -o - | ffmpeg -ss 10 -i pipe:0 -acodec pcm_s16le -ac 1 -ar 16000 piped.wav

# function fetch_metadata () {
#   yt-dlp --dump-json $YT_URL > $FILES_DIR/yt_metadata.json
# }
# yt-dlp --list-subs --skip-download "https://www.youtube.com/watch?v=jm3JFYqvQxw"

